name: gedik_mobil
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  google_sign_in: ^6.1.0
  cloud_firestore: ^6.1.0
  firebase_app_check: ^0.4.1+2

  # Notifications
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2

  # Harita yÃ¶nlendirme
  url_launcher: ^6.2.5

  # HTML parsing
  http: ^1.2.0
  html: ^0.15.4
  xml: ^6.6.1

  # Google Generative AI
  genai: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # ðŸ”¥ APP ICON
  flutter_launcher_icons: ^0.13.1

# ðŸ”¥ ICON CONFIG
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/
